### ISSUE TITLE
Create an application for an external NSM client

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/cmd-nsc-simple-docker#1]
### Description
This application allows the client to connect to NSM from outside.
See the diagram below: 
![external_nsc drawio](https://user-images.githubusercontent.com/17748275/174532484-aa0d884d-d174-4c5e-aa72-b71bc8b30ab5.svg)

The application will be a combination of [NSC](https://github.com/networkservicemesh/cmd-nsc) and [Forwarder](https://github.com/networkservicemesh/cmd-forwarder-vpp)

**Comment by glazychev-art** [comment]
@edwarnicke 
Is this the right direction?

**Comment by edwarnicke** [comment]
As far as the picture goes: yes  :)

I am a little confused by the client part and server part labels as those are sort of the opposite of what I would expect... but I suspect you have a well thought out reason why they are the way they are.  Could you provide some more detail?

**Comment by glazychev-art** [comment]
@edwarnicke 
You are right :) The picture was updated

**Comment by glazychev-art** [comment]
@edwarnicke 
I think it's almost like that.
But, it's worth remembering that in a typical scenario, we have the NSC and the Forwarder as two different application - NSC requests (puts something in the mechanism preferences), and the Forwarder creates. I.e
NSC(_**client chain**_) .... ----> Forwarder (_**server chain + client chain**_) ----> .....

In this scenario, we need to combine the client and the forwarder into one chain:
cmd-nsc-simple-docker (**_client chain + server chain + client chain_**) -----> ......

We need to figure out whether only _**server + client**_ is enough for us

**Comment by glazychev-art** [comment]
Eventually `cmd-nsc-simple-docker` will contain:

```
//    ┌─────────┐      ┌───────────────┐
//    │         │      │               │   Request()
//    │   NSC   ├─────►│   Local FWD   ├───────────────────► [k8s] nsmgr-proxy
//    │         │      │               │
//    └─────────┘      └──────┬────────┘
//                            │discover
//                            │
//                     ┌──────▼────────┐
//                     │               │    Find()
//                     │Proxy  Registry├───────────────────►[k8s] registry
//                     │               │
//                     └───────────────┘
```

`NSC` - sends a Request to the local Forwarder. Supports `retry` and `heal`
`Local Fwd` - finds an NSE (using proxy registry), creates local and remote mechanisms
`Proxy Registry` - handles a request by domain (interdomain scenario)

**Comment by edwarnicke** [comment]
@glazychev-art Are these separate processes or simply logical components?

You are correct about the *functionality* that is needed... but we should be able to put these together into a simple docker NSC as a single process by stringing together various chain elements.

**Comment by glazychev-art** [comment]
@edwarnicke 
I meant that all these components can be run as one process, in one binary file, but it will have 3 different chains (NSC, Fwd, Proxy registry) and 2 grpc services on unix sockets (forwarder and registry).

If we want to have only **_one_** chain for the entire application, then there are a couple of possible problems:
1. The chain will include **_client - server - client_**. Now this cannot be done, at least because of the metadata, because there can only be one for the client and one for the server.
2. We almost completely reuse the long forwarder-vpp chain. And when we need to add a feature or fix a bug, we will need to remember two places (forwarder-vpp and cmd-nsc-simple-docker)

**Comment by glazychev-art** [comment]
@edwarnicke 
`discover` has `registry.NetworkServiceRegistryClient`, so, probably we can construct a new registry chain for discovering.

Client (I mean the first part, NSC) has not only healing, but refresh, retry and mechanism preferenses with kernel interface parameters. So I think this part will be more difficult.

**Comment by edwarnicke** [comment]
@glazychev-art Got it... so we could in principle just have the *server - client* listen on a unix file socket inside the container and have the in-process client talk to that... but at that point the only real difference between that and what you have is rolling the DNS resolution bits into a new chain element (and working out a use specific chain).

I can see now why you decided it was a better idea to do what you are doing.

**Comment by edwarnicke** [comment]
@denis-tingaikin I presume #2 also includes merging cmd-nsc-simple-docker as it is written this moment for release in v1.5.0?

**Comment by glazychev-art** [comment]
Closed with https://github.com/networkservicemesh/cmd-nsc-simple-docker/pull/2
